master: ""
ring: "DATA"
path: "/fs/spark/"
protocol: file
srebuildd_ip: "127.0.0.1"
srebuildd_path: "/rebuild/chord"
srebuildd_single_path: "rebuild/arc-DATA"
srebuildd_double_path: "rebuild/arcdata-DATA"
retention: 604800
arc_protection: 8+4
s3:
  access_key: ""
  secret_key: ""
  endpoint: ""
sup:
  url: "https://127.0.0.1:2443"
  login: "root"
  password: ""
spark.executor.cores: 6
spark.executor.instances: 6
spark.executor.memory: "8g"
spark.driver.memory: "8g"
spark.memory.offHeap.enabled: True
spark.memory.offHeap.size: "6g"
