master: ""
ring: "DATA"
path: "/fs/spark/"
protocol: file      # Protocol can be either file or s3a.
# Protocol file requires SOFS+DLM & path is the folder to write to within the SOFS volume.
# Protocol s3a requires access/secret keys & endpoint URL & path is the bucket name within s3 to use.
srebuildd_ip: "127.0.0.1"
srebuildd_chord_path: "/rebuild/chord-DATA"
srebuildd_arc_path: "rebuild/arc-DATA"
srebuildd_arcdata_path: "rebuild/arcdata-DATA"
retention: 604800
arc_protection: 8+4
cos_protection: 3
s3:
  access_key: ""
  secret_key: ""
  endpoint: ""
sup:
  url: "https://127.0.0.1:2443"
  login: "root"
  password: ""
spark.executor.cores: 6
spark.executor.instances: 6
spark.executor.memory: "8g"
spark.driver.memory: "8g"
spark.memory.offHeap.enabled: True
spark.memory.offHeap.size: "6g"
