FROM openjdk:8-alpine
RUN apk --update add wget tar bash
RUN apk --no-cache add bash procps python R py-pip
RUN pip install requests
RUN wget http://apache.mirror.anlx.net/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz

RUN tar -xzf spark-2.4.3-bin-hadoop2.7.tgz && \
    mv spark-2.4.3-bin-hadoop2.7 /spark && \
    rm spark-2.4.3-bin-hadoop2.7.tgz

COPY start-worker.sh /start-worker.sh
RUN chmod +x /start-worker.sh

ENTRYPOINT ["/start-worker.sh"]
