---

- name: Ensure sidecar config and log directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /etc/scality/spark/sidecar
    - /var/log/scality/spark/sidecar

- name: Deploy sidecar config
  template:
    src: ./sidecar-nginx.conf.j2
    dest: /etc/scality/spark/sidecar/nginx.conf
    mode: 0640

- name: Copy start_sidecar.sh
  template:
    src: start_sidecar.sh.j2
    dest: /usr/local/bin/start_sidecar.sh
    mode: 0744
  tags:
    - run::configs

- name: Copy stop_sidecar.sh
  template:
    src: stop_sidecar.sh.j2
    dest: /usr/local/bin/stop_sidecar.sh
    mode: 0744
  tags:
    - run::configs

- name: Stop any running sidecar container
  shell: |
    /usr/local/bin/stop_sidecar.sh ; /usr/local/bin/start_sidecar.sh

- name: Start the sidecar container.
  shell: |
    /usr/local/bin/stop_sidecar.sh ; /usr/local/bin/start_sidecar.sh