---

  - block:
    - name: Ensure staging directory exists
      file:
        state: directory
        path: "{{ staging_path }}"

    - name: Synchronize the master image
      synchronize:
        src: "{{ staging_path }}{{ item.split(':')[0].split('/')[-1] }}.tar"
        dest: "{{ staging_path }}"
      with_items:
        - "{{ master_container_image }}"
  
    - name: Deploy the spark repository on spark master
      unarchive:
        src: "{{ staging_path }}spark-repo.tar"
        dest: /root/

    - name: Ensure spark config directory exists
      file:
        state: directory
        path: /root/spark/scripts/config

    tags:
      - run::deployment  
    when:
      - inventory_hostname in groups['sparkmaster'] |default([])

  - block:
    - name: Synchronize the workers images
      synchronize:
        src: "{{ staging_path }}{{ item.split(':')[0].split('/')[-1] }}.tar"
        dest: "{{ staging_path }}"
      with_items:
        - "{{ worker_container_image }}"
        - "{{ s3utils_container_image }}"
        - "{{ nginx_container_image }}"

    tags:
      - run::deployment
    when:
      - inventory_hostname in groups['sparkworkers']|default([])

  - include: '{{ ansible_os_family | lower }}.yml'
