---
- hosts: sparkworkers:!runners_s3:!runners_srebuildd
  tasks:
    - name: Obtain the nginx image tag installed
      shell: |
        docker images nginx | awk '/^nginx/ {print $2}'
      register: nginx_image_version

    - name: debug the content
      debug:
        msg: The values are {{ nginx_image_version }}
      tags:
        - never
        - debug

    - name: deploy the sidecar container.
      shell: |
        docker run -dit --rm \
          --net host \
          --name sidecar \
          -v /var/log/scality/spark/sidecar:/logs/:rw \
          -v /etc/scality/spark/sidecar/nginx.conf:/etc/nginx/nginx.conf:ro \
          nginx:{{nginx_image_version.stdout }}

- hosts: sparkworkers:!runners_s3
  tasks:
    - name: Obtain the nginx image tag installed
      shell: |
        docker images nginx | awk '/^nginx/ {print $2}'
      register: nginx_image_version

    - name: debug the content
      debug:
        msg: The values are {{ nginx_image_version }}
      tags:
        - never
        - debug

    - name: deploy the sidecar container.
      shell: |
        docker run -dit --rm \
          --net host \
          --name sidecar \
          -v /var/log/scality/spark/sidecar:/logs/:rw \
          -v /etc/scality/spark/sidecar/nginx.conf:/etc/nginx/nginx.conf:ro \
          nginx:{{nginx_image_version.stdout }}

- hosts: sparkworkers:!runners_srebuildd
  tasks:
    - name: Obtain the nginx image tag installed
      shell: |
        docker images nginx | awk '/^nginx/ {print $2}'
      register: nginx_image_version

    - name: debug the content
      debug:
        msg: The values are {{ nginx_image_version }}
      tags:
        - never
        - debug

    - name: deploy the sidecar container.
      shell: |
        docker run -dit --rm \
          --net host \
          --name sidecar \
          -v /var/log/scality/spark/sidecar:/logs/:rw \
          -v /etc/scality/spark/sidecar/nginx.conf:/etc/nginx/nginx.conf:ro \
          nginx:{{nginx_image_version.stdout }}