---
- hosts: staging
  roles:
    - role: stage-spark-cluster
      tags:
        - never
        - stage

- hosts: sparkmaster:sparkworkers
  roles:
    - role: run-spark-cluster
      tags:
        - never
        - deploy

- hosts: sparkmaster
  roles:
    - role: create-sample-config
      tags:
        - never
        - deploy
        - run::configs
        - run::config-sample
        
- hosts: sparkworkers:!runners_s3:!runners_srebuildd
  roles:
    - role: run-spark-sidecar
      tags:
        - never
        - sidecar

- hosts: sparkworkers:!runners_s3
  roles:
    - role: run-spark-sidecar
      tags:
        - never
        - sidecar

- hosts: sparkworkers:!runners_srebuildd
  roles:
    - role: run-spark-sidecar
      tags:
        - never
        - sidecar
