---
- hosts: staging
  roles:
    - role: stage-spark-cluster
      vars:
        stage: True
      tags:
        - never
        - stage

- hosts: sparkmaster:sparkworkers
  roles:
    - role: run-spark-cluster
      tags:
        - deploy
      when: not stage | bool
