name: Create Prerelease on tag creation

on:
  push:
    tags:
      - "*"

jobs:
  call-release-workflow:
    environment: packages
    uses: scality/spark/.github/workflows/release.yml@master
    with:
      tag: ${{ github.ref_name }}
      prerelease: true
    secrets: inherit